version: "3.8"

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
