name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'kpu-cpp-project'

      - name: Authenticate Docker with Google Cloud
        run: gcloud auth configure-docker

      - name: Build and push Docker image for frontend
        run: |
          docker build -t gcr.io/kpu-cpp-project/frontend-service ./frontend
          docker push gcr.io/kpu-cpp-project/frontend-service

      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy frontend-service \
            --image gcr.io/kpu-cpp-project/frontend-service
